/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Master
 */
public class OlaMundoSwing extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OlaMundoSwing.class.getName());

    /**
     * Creates new form OlaMundoSwing
     */
    public OlaMundoSwing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setText("Insira um número");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jTextField2.setText("Insira um número");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel2.setText("Resultado:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jButton5.setText("Calcular");
        jButton5.addActionListener(this::jButton5ActionPerformed);
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-", "*", "/", "^", "%", "√" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jButton1.setText("Limpar");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
if (jTextField1.getText().equals("") || jTextField2.getText().equals("")) {
   jLabel2.setText("Preencha os dois campos!");
    } else {
   
    try {
double numero1 = Double.parseDouble(jTextField1.getText());
double numero2 = Double.parseDouble(jTextField2.getText());

String operacao = jComboBox1.getSelectedItem().toString();

if (operacao.equals("+")) {
        double resultado = numero1 + numero2;
        jLabel2.setText("Resultado: " + resultado);

    } else if (operacao.equals("-")) {
        double resultado = numero1 - numero2;
        jLabel2.setText("Resultado: " + resultado);

    } else if (operacao.equals("*")) {
        double resultado = numero1 * numero2;
        jLabel2.setText("Resultado: " + resultado);
        
    } else if (operacao.equals("/")) {
        if (numero2 == 0) {
            jLabel2.setText("Não é possível dividir por zero!");
        } else  {
            double resultado = numero1 / numero2;
            jLabel2.setText("Resultado: " + resultado);
        }
    } else if (operacao.equals("^")) {
    double resultado = Math.pow(numero1, numero2);
    jLabel2.setText("Resultado: " + resultado);
        }
    else if (operacao.equals("%")) {
    double resultado = numero1 * numero2 / 100;
    jLabel2.setText("Resultado: " + resultado);
}
    else if (operacao.equals("√")) {
    
    double resultado = Math.sqrt(numero1);
    
    jLabel2.setText("Resultado: " + resultado);
}

     else {
        jLabel2.setText("Operação inválida!");
    }
} catch (Exception e) {
    jLabel2.setText("Digite apenas números!");
}
    }//GEN-LAST:event_jButton5ActionPerformed
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
jTextField1.setText("");
jTextField2.setText("");
jLabel2.setText(""); 
jComboBox1.setSelectedItem("+");// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new OlaMundoSwing().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
